### ISSUE TITLE
Missing libiconv-2.dll for st3_windows_x32/etree.pyd

### ISSUE THREAD

**Issue by elupus** [eerohele/sublime-lxml#7]
Plugin exalt fail to load with error:

```
reloading plugin Exalt.impl.plugin
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 210, in on_api_ready
    m.plugin_loaded()
  File "C:\Users\jopl\AppData\Roaming\Sublime Text 3\Packages\Exalt\exalt.py", line 85, in plugin_loaded
    sublime_plugin.reload_plugin("%s.impl.plugin" % constants.PLUGIN_NAME)
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 109, in reload_plugin
    m = importlib.import_module(modulename)
  File "./python3.3/importlib/__init__.py", line 90, in import_module
  File "<frozen importlib._bootstrap>", line 1584, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1565, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1532, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 584, in _check_name_wrapper
  File "<frozen importlib._bootstrap>", line 1022, in load_module
  File "<frozen importlib._bootstrap>", line 1003, in load_module
  File "<frozen importlib._bootstrap>", line 560, in module_for_loader_wrapper
  File "<frozen importlib._bootstrap>", line 868, in _load_module
  File "<frozen importlib._bootstrap>", line 313, in _call_with_frames_removed
  File "C:\Users\jopl\AppData\Roaming\Sublime Text 3\Packages\Exalt\impl\plugin.py", line 28, in <module>
    from lxml import etree
ImportError: DLL load failed: Det går inte att hitta den angivna modulen.
```
"Det går inte att hitta den angivna modulen." swedish for can't find the module.

dependency walker on the etree.pyd reveal it needs libiconv-2.dll. This is on win32

**Comment by eerohele** [comment]
I don’t have a 32-bit Windows installation to test this on, I’m afraid. Win32 support was contributed by @debjan. Do you have any insight on what might be going on?

**Comment by debjan** [comment]
Hi,

unfortunately I dont have 32 bit windows also. However checking `../Packages/lxml/st3_windows_x32` shows that these are not the files I commited as in https://github.com/eerohele/sublime-lxml/pull/4/files

Several libraries are renamed, and current module is compiled by someone else it seems.

**Comment by debjan** [comment]
There seems to be a problem also with 64 bit Windows.

Installing https://github.com/rosshadden/sublime-xpath installs lxml w/o issues on 64 bit Windows, but when I try to install exalt, then it seems like it tries to update lxml and it fails, for some reason.

**Comment by eerohele** [comment]
That's odd. I don't currently have access to Windows box at all so I can't really test any of this. However, I've had reports of the 64-bit version working for other people, at least…

**Comment by eerohele** [comment]
@debjan, @elupus: sublime-lxml v0.6.0 (as delivered by @deathaxe) should fix the issue.

Could you give it a try and let me know how it goes? I think you need to run the **Package Control: Satisfy Dependencies** command via the Sublime Text command palette to get the new version of the sublime-lxml dependency.

**Comment by eerohele** [comment]
I'll close this issue, but if the latest version doesn't fix the problem for you, please let me know and I'll reopen it.
